/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CheckCircleOutlined: typeof import('@ant-design/icons-vue')['CheckCircleOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
