/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BellOutlined: typeof import('@ant-design/icons-vue')['BellOutlined']
    CheckCircleOutlined: typeof import('@ant-design/icons-vue')['CheckCircleOutlined']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DashboardOutlined: typeof import('@ant-design/icons-vue')['DashboardOutlined']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    FormOutlined: typeof import('@ant-design/icons-vue')['FormOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    StarFilled: typeof import('@ant-design/icons-vue')['StarFilled']
  }
}
